config/routes.rb
Rails.application.routes.draw do
  # get 'schedules/index'
  root "schedules#index"
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validate :check_date

  def check_date
    if start_date < Date.today
      errors.add(:start_date, "に過去日は指定できません")
    elsif end_date < Date.today
      errors.add(:end_date, "に過去日は指定できません")
    elsif end_date < start_date
      errors.add(:end_date, "に開始日より前の日は指定できません")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title,:start_date,:end_date,:all_day,:schedule_memo))
    if @schedule.save
      flash[:notice] = "スケジュールを登録しました" #ハッシュで格納し、ビューで呼び出す。
      redirect_to :schedules
    else
      render :new #指定したアクションが動く。
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title,:start_date,:end_date,:all_day,:schedule_memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :schedules
    else
      render :edit
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to :schedules
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
  </body>
</html>

app/views/schedules/edit.html.erb
<div class = "main-container">
  <h2>スケジュール編集</h2>

  <%= form_with model:@schedule do |f| %>

    <table>
      <tr>
        <th><%= f.label :title, "タイトル" %></th>
        <td><%= f.text_field :title %></td>
      </tr>

      <tr>
        <th><%= f.label :start_date, "開始日" %></th>
        <td><%= f.date_field :start_date %></td>
      </tr>

      <tr>
        <th><%= f.label :end_date, "終了日" %></th>
        <td><%= f.date_field :end_date %></td>
      </tr>

      <tr>
        <th><%= f.label :all_day, "終日" %></th>
        <td>
          <%= f.check_box :all_day %>
          終日の場合はチェックを入れます
        </td>

      <tr>
        <th><%= f.label :schedule_memo, "スケジュールメモ" %></th>
        <td><%= f.text_area :schedule_memo, class: "posts-content" %></td>
      </tr>
    </table>

    <div>
      <ul>
        <li><%= f.submit "スケジュールの編集を完了する" %></li>
        <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
      </ul>
    </div>
  <% end %>

</div>

<footer>
  <%= render "shared/footer" %>
</footer>

app/views/schedules/index.html.erb
<div class = "main-container">

<h2>スケジュール一覧</h2>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日</th>
        <th>スケジュール更新日時</th>
        <th>確認</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>

    <tbody>
      <% @schedules.each do |schedule| %>
        <tr>
          <td><%= schedule.id %></td>
          <td><%= schedule.title %></td>
          <td><%= schedule.start_date %></td>
          <td><%= schedule.end_date %></td>
          <% if schedule.all_day == "1" %>
            <td>○</td>
          <% else %>
            <td> </td>
          <% end %>
          <td><%= schedule.updated_at.to_s(:datetime_jp_ymdhm) %></td>
          <td><%= link_to "確認", schedule %></td>
          <td><%= link_to "編集", [:edit,schedule] %></td>
          <td><%= link_to "削除", schedule, method: :delete, data: {confirm:"本当に削除しますか？"} %></td>
        </tr>
      <% end %>
    </tbody>

  </table>

  <p><%= link_to "スケジュール新規登録", :new_schedule %></p>

</div>

<footer>
  <h1>現在の日時 : <%= Date.today.strftime("%Y年%m月%d日")%> スケジュール合計 : <%= @schedules.count%></h1>
</footer>

app/views/schedules/new.html.erb
<div class = "main-container">
  <h2>スケジュール新規作成</h2>

  <%= render "shared/error" %>

  <%= form_with model:@schedule do |f| %>

    <table>
      <tr>
        <th><%= f.label :title, "タイトル" %></th>
        <td><%= f.text_field :title %></td>
      </tr>

      <tr>
        <th><%= f.label :start_date, "開始日" %></th>
        <td><%= f.date_field :start_date %></td>
      </tr>

      <tr>
        <th><%= f.label :end_date, "終了日" %></th>
        <td><%= f.date_field :end_date %></td>
      </tr>

      <tr>
        <th><%= f.label :all_day, "終日" %></th>
        <td>
          <%= f.check_box :all_day %>
          終日の場合はチェックを入れます
        </td>

      <tr>
        <th><%= f.label :schedule_memo, "スケジュールメモ" %></th>
        <td><%= f.text_area :schedule_memo, class: "posts-content" %></td>
      </tr>
    </table>

    <div>
    <% #submit、引数（@schedule）が何も情報を持っていなければcreateアクション、何かしらの情報を持っているのであればupdateアクションに送信される %>
        <ul>
          <li><%= f.submit "スケジュールを新規登録する" %></li>
          <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
        </ul>
    </div>
  <% end %>

</div>

<footer>
  <%= render "shared/footer" %>
</footer>

app/views/schedules/show.html.erb
<div class = "main-container">
  <h2>スケジュール詳細</h2>

  <table>
      <tr>
        <th>タイトル</th>
        <td><%= @schedule.title %></td>
      </tr>
      <tr>
        <th>開始日</th>
        <td><%= @schedule.start_date %></td>
      </tr>
      <tr>
        <th>投稿日時</th>
        <td><%= @schedule.created_at.to_s(:datetime_jp_ymd) %></td>
      </tr>
      <tr>
        <th>終日</th>
        <% if @schedule.all_day == "1" %>
          <td>○</td>
        <% else %>
          <td> </td>
        <% end %>
      </tr>
      <tr>
        <th>スケジュールメモ</th>
        <td>
          <pre><%= @schedule.schedule_memo %></pre>
        </td>
      </tr>
  </table>

  <div>
    <ul>
      <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
      <li><%= link_to "スケジュールを編集する", edit_schedule_path(@schedule) %></li>
      <li><%= link_to "スケジュールを削除", @schedule, method: :delete, data: {confirm:"本当に削除しますか？"} %></li>
    </ul>
  </div>
</div>

<footer>
  <%= render "shared/footer" %>
</footer>

app/views/shared/_error.html.erb
<% if @schedule.errors.any? %>
  <p><% @schedule.errors.full_messages.each do |message| %> </p>
  <p><%= message %></p>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<h1>現在の日時 : <%= Date.today.strftime("%Y年%m月%d日") %></h1>